# Generated by Django 4.2.4 on 2023-08-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('excited_about', models.CharField(blank=True, max_length=200, null=True)),
                ('free_time', models.CharField(blank=True, max_length=200, null=True)),
                ('fav_book', models.CharField(blank=True, max_length=200, null=True)),
                ('fav_food', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
