# Generated by Django 4.2.4 on 2023-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_studentprofile_data_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
