# Generated by Django 4.2.4 on 2023-08-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_studentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
