# Generated by Django 4.2.4 on 2023-08-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images.png', null=True, upload_to=''),
        ),
    ]
