# Generated by Django 4.2.4 on 2023-08-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_rename_excited_about_teacherprofile_inst_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
