# Generated by Django 4.2.4 on 2023-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_teacherprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
