# Generated by Django 4.2.4 on 2023-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_studentprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepics/images.png', null=True, upload_to=''),
        ),
    ]
