# Generated by Django 4.2.4 on 2023-08-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='excited_about',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fav_book',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fav_food',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='free_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
