# Generated by Django 4.2.4 on 2023-08-20 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_logbook_benefits_logbook_blueprint_logbook_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
