# Generated by Django 4.2.4 on 2023-08-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_logbook_description_alter_logbook_inventor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='inventor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='schoolnamegrade',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='sig1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='sig2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
