# Generated by Django 4.2.4 on 2023-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_logbook_description_alter_logbook_inventor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='benefits',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='blueprint',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='buy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='customer_age',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='customer_education',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='customer_gender',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='customer_house',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='customer_marital',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='describe_problem',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='design_problem',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='factors',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='findings',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='green_sol',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='initial_problem',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='invention',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='materials',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='nameinvention',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='negative',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='other_notes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='positive',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='prototype',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='prototype_pic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='research',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='selected_problem',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='sig1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='sig2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='sig3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='sig4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='sol_design_problem',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='specific_sol',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='testing',
            field=models.CharField(default='', max_length=200),
        ),
    ]
