# Generated by Django 4.2.4 on 2023-08-21 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_logbook_benefits_alter_logbook_blueprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='data_created',
            field=models.DateTimeField(default=datetime.date(2023, 8, 22)),
        ),
    ]
