# Generated by Django 4.2.4 on 2023-08-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_logbook_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='note_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logbook',
            name='note_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
