# Generated by Django 4.2.4 on 2023-08-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_logbook_note_desc_logbook_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='difficulty',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logbook',
            name='future',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logbook',
            name='thanking',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logbook',
            name='things_enjoyed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
