# Generated by Django 4.2.4 on 2023-08-23 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_logbook_difficulty_logbook_future_logbook_thanking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='data_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 23, 17, 26, 30, 820326, tzinfo=datetime.timezone.utc)),
        ),
    ]
