# Generated by Django 4.2.4 on 2023-08-25 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0024_alter_logbook_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_logbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
