# Generated by Django 4.2.4 on 2023-08-25 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0025_logbook_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='members',
            field=models.ManyToManyField(blank=True, default=list, related_name='joined_logbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
