# Generated by Django 4.2.4 on 2023-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_logbook_benefits_alter_logbook_blueprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
