# Generated by Django 4.2.4 on 2023-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_alter_logbook_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbook',
            old_name='description',
            new_name='member2',
        ),
        migrations.AddField(
            model_name='logbook',
            name='member3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='member4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='member5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='member6',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
