# Generated by Django 4.2.4 on 2023-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_rename_description_logbook_member2_logbook_member3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='schoolnamegrade2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='schoolnamegrade3',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='schoolnamegrade4',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='schoolnamegrade5',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='schoolnamegrade6',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
